# Generated by Django 4.2.4 on 2023-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='beammodel',
            name='reference_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
