# Generated by Django 4.2.4 on 2023-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_mymodel_beammodel_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beammodel',
            name='elasticity',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='inertia',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='length',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='lengthunit',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='loadunit',
        ),
        migrations.AlterField(
            model_name='beammodel',
            name='beam',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
