# Generated by Django 4.2.4 on 2023-09-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RenameField(
            model_name='beammodel',
            old_name='distributedload_input',
            new_name='beam',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='point_load_input',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='support_input',
        ),
        migrations.AddField(
            model_name='beammodel',
            name='lengthunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beammodel',
            name='loadunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beammodel',
            name='elasticity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beammodel',
            name='inertia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beammodel',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
