# Generated by Django 4.2.4 on 2023-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_beammodel_plots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beammodel",
            name="elasticity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beammodel",
            name="inertia",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beammodel",
            name="length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beammodel",
            name="nodes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
