# Generated by Django 4.2.4 on 2023-09-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_beammodel_elasticity_alter_beammodel_inertia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beammodel',
            old_name='distributedload_input',
            new_name='beam',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='plots',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='point_load_input',
        ),
        migrations.RemoveField(
            model_name='beammodel',
            name='support_input',
        ),
        migrations.AddField(
            model_name='beammodel',
            name='lengthunit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beammodel',
            name='loadunit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
